### ISSUE TITLE
Uncaught (in promise) TypeError: vue__WEBPACK_IMPORTED_MODULE_0__.unref(...) is undefined

### ISSUE THREAD

**Issue by jugurtha114** [n1crack/vuefinder#12]
hello, i get this error when i delete files :
`Uncaught (in promise) TypeError: vue__WEBPACK_IMPORTED_MODULE_0__.unref(...) is undefined`

**Comment by jowebdev** [comment]
> hello, i get this error when i delete files : `Uncaught (in promise) TypeError: vue__WEBPACK_IMPORTED_MODULE_0__.unref(...) is undefined`

I have the same problem, did you find a solution, or did you find another component?

**Comment by n1crack** [comment]
It is highly possible the ajax returns an invalid response.

Can you provide what returns from the ajax request like:

![image](https://github.com/n1crack/vuefinder/assets/712404/8078fa49-e37c-422d-8713-a4cc256f8add)
