### ISSUE TITLE
Choose dark mode based on browser settings

### ISSUE THREAD

**Issue by MLDMoritz** [n1crack/vuefinder#15]
For my project I used Tailwind and so we're using the dark: classes too. Is there a way to let the browser decide which version it should use, without having to code a check? I did this, but unlucky:

```js
const prefersDark = ref(false);

onMounted(() => {
    prefersDark.value = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
});

const isDarkMode = computed(() => prefersDark.value);
```

```vue
<VueFinder id="finder" :url="`/filemanager/order/${order.id}`" :dark="isDarkMode" locale="de"></VueFinder>
```

**Comment by n1crack** [comment]
updated the script, added usePropDarkMode, it hides the dark mode selector button and only gets the variable from props if it ise selected. so you can set it outside the component now

<VueFinder id="finder" :url="`/filemanager/order/${order.id}`" :dark="isDarkMode" usePropDarkMode locale="de"></VueFinder>

**Comment by MLDMoritz** [comment]
Looking good! I also found a typo in Toolbar: `Unrchive`, seems it didn't get thru my pull request.

I also fixed a bug in the PHP adapter.

Could you create a new release of the changes?

**Comment by n1crack** [comment]
done. Thank you.

**Comment by MLDMoritz** [comment]
Think it should hide the theme switch button, but thats just asthetics. Ty!

**Comment by n1crack** [comment]
It is hidden when using usePropDarkMode

https://github.com/n1crack/vuefinder/blob/57719a0022df966e6a8f122d7fb2e4a0452bd30a/src/components/Toolbar.vue#L82C23-L82C38
