### ISSUE TITLE
Showing error on npm install

### ISSUE THREAD

**Issue by emtiazzahid** [n1crack/vuefinder#2]
Showing error on npm install

` error  in ./node_modules/vuefinder/src/components/Explorer.vue?vue&type=style&index=0&id=2c3bb2b3&lang=scss&scoped=true&

Syntax Error: SassError: expected selector.
   ╷
81 │ /deep/ .vuefinder-items-enter-active{
/Sites/vehicle/node_modules/vuefinder/src/components/Explorer.vue 81:1  root stylesheet
`

Node version: v12.18.1
NPM version: 6.14.11

**Comment by n1crack** [comment]
im closing the issue because the component was created almost from scratch
