### ISSUE TITLE
File download ignoring "url" property (if present) on file entries?

### ISSUE THREAD

**Issue by peebles** [n1crack/vuefinder#28]
In ContextMenu.vue:

```js
download: {
    title: () =>  t('Download'),
    action: () => {
      const url = apiUrl.value + '?' + buildURLQuery({q:'download', adapter: props.current.adapter, path: selectedItems.value[0].path});
      emitter.emit('vf-download', url);
    },
  },
```

But some file entries might have a "url" property and it seems to me that this property should be used as the url to pass to vf-download.  An adapter on the server side like S3 might be returning pre-signed S3 urls for files, right?  Your vuefinder-php backend is:

```php
$config = [
    'publicLinks' => [
        'local://public' => 'http://example.test',
    ],
];
```

and for files in the public folder, the url property is set to http://example.test/...  but the vuefinder component is not downloading from this location, its calling APIURL?q=download instead.

Is this an oversite, or am I doing something wrong?  In my use case, my backend is a lot like S3 and will return "url" properties for files, and I need the client to download from those urls.

**Comment by n1crack** [comment]
You are right. That's something we missed. Downloading must be from those links.

**Comment by n1crack** [comment]
solved
