### ISSUE TITLE
deep Error

### ISSUE THREAD

**Issue by cyrixSpec** [n1crack/vuefinder#3]
Hi there,
thank you for your great file browser.
At the moment I get the following message

` error  in ./node_modules/vuefinder/src/components/FilePreviewer.vue?vue&type=style&index=0&id=5a99ec95&lang=scss&scoped=true&

SassError: expected selector.
   ╷
95 │   /deep/ .vuefinder-text-preview{
   │   ^
   ╵
`
Maybe you have a fix for that ?

Thanks in advance.

**Comment by n1crack** [comment]
im closing the issue because the component was created almost from scratch
