### ISSUE TITLE
Preflight styles applying to elements outside of component

### ISSUE THREAD

**Issue by Daedalus11069** [n1crack/vuefinder#42]
This is related to #31, wherein the following code(reduced for brevity), was added to the tailwind config:

```js
preflightStyles.walkRules((rule) => {
    rule.selector = ".vuefinder " + rule.selector;
});
```

While this works for the most part, it's still causing a leak because the preflight uses commas in several rules.  I wasn't sure if creating a repo/PR for this was overkill because of how minor the change is, so here's the simple bug report/fix.

I was able to fix this on my side with a simple change to the above:

```js
preflightStyles.walkRules(rule => {
  rule.selector = rule.selectors
    .map(selector => ".vuefinder " + selector)
    .join(",");
});
```

**Comment by n1crack** [comment]
I don't think its minor. This can cause many style issues. 

And the solution seems good to me.

**Comment by matamune94** [comment]
I'm having an error on tailwindcss 4.0, the variable is being overwritten, is there any way to solve it?
