### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by meer-sagor** [n1crack/vuefinder#44]
I encountered a challenge related to CSS overriding within version 1.2.5 of our project. In an attempt to find relevant documentation or discussions addressing this issue, I conducted a thorough search but found no pertinent resources. Subsequently, I opted to proceed with upgrading the project version.

Upon initiating the installation process, I observed that the update incremented by only a minor version, leaving the project at version 1.2.6. However, upon further investigation, I discovered that the latest available version stands at 2.2.2.

**Comment by n1crack** [comment]
can you show me the content of package.json file.

**Comment by n1crack** [comment]
hm it seems we skipped the version 1.2.6, it is not in the npm dir. 

Do you any problem after you updated to 2.x version?  I tried to install it and it seems ok to me.

**Comment by meer-sagor** [comment]
> hm it seems we skipped the version 1.2.6, it is not in the npm dir.
> 
> Do you any problem after you updated to 2.x version? I tried to install it and it seems ok to me.

It works great for me. but need to update the document. The previous version take: `url` props for data fetching but the current version take `request` props. otherwise everything works fine for me

**Comment by n1crack** [comment]
yea thats why we increased the major number.  

1.3.3 is the latest before 2.x branch
