### ISSUE TITLE
Vuefinder locale doesnt work and download files twice

### ISSUE THREAD

**Issue by alejandromsagui** [n1crack/vuefinder#47]
I'm using Vuefinder with Nuxt 3 and set it up as a plugin. It's an awesome library, but I have two problems

When I try to change the default language of the library to another one, it never gets changed and always displays in English. This is the configuration of my Vuefinder plugin:

```
import 'vuefinder/dist/style.css';
import VueFinder from 'vuefinder/dist/vuefinder';

export default defineNuxtPlugin(({ vueApp }) => {

    vueApp.use(VueFinder, {
        i18n: {  es: async () => await import("vuefinder/dist/locales/es.js") }
      });
});
```

And this is how I call Vuefinder in a view:

```
<template>
    <div>
        <VueFinder :request="request" locale="es"></VueFinder>
    </div>
</template>
<script setup>
const request = `apiUrl`
</script>
```

The second problem is that when I download a file, it usually downloads twice. I have also been investigating the example displayed, and this problem also occurs. 

In the following image you can see how a download is performed twice in the displayed example

![image](https://github.com/n1crack/vuefinder/assets/93497327/6c9fe855-176e-40ab-8e6c-30f8b0c9dc47)

Thanks in advance!

**Comment by n1crack** [comment]
I will look at the issues asap.
