### ISSUE TITLE
Missing auth token in download requests

### ISSUE THREAD

**Issue by darkleizar** [n1crack/vuefinder#48]
With this configuration

script...

```
const accessToken = useCookie('accessToken').value
const request = {
  baseUrl: "/api/auth/vuefinder/"+ currentId,
  headers: { Authorization: `Bearer ${accessToken}`, Accept :'application/json'}
}
const vuefinderFeatures = [
  'download',
  'search'
];
```

template...
`<vue-finder id="vf" theme="light" :features="vuefinderFeatures" :request="request" :select-button="handleSelectButton"></vue-finder>`

the download action is performed without the Bearer token

**Comment by n1crack** [comment]
https://github.com/n1crack/vuefinder/issues/45

**Comment by n1crack** [comment]
since it is duplicated with the other issue, Im closing this.  Im looking for the best solution for this issue.  we need to figure out how can it be implemented for "stateless auths".
