### ISSUE TITLE
the lazy load img is lose efficacy when you enter dir ,it will show wrong img

### ISSUE THREAD

**Issue by shengxiange** [n1crack/vuefinder#51]
when I explore the  demo web ,https://vuefinder.ozdemir.be/
I  find the problem，
![image](https://github.com/n1crack/vuefinder/assets/57220214/0ac616ed-03a6-4353-be2f-de722f513243)

this pic will same show in the images dir file list!
![image](https://github.com/n1crack/vuefinder/assets/57220214/681815e2-1b2d-4ba9-90b3-6936880d8421)

in fact ,the right img is exactly that 
![image](https://github.com/n1crack/vuefinder/assets/57220214/41166317-1743-4439-a967-e6811a62a711)

I use vuefinder in my vue3 project , meet the same problem also yet .
I guess it maybe  caused by the vanilla-lazyload running failed.

**Comment by n1crack** [comment]
thanks for reporting.. It is fixed now.
