### ISSUE TITLE
Localisation Select button

### ISSUE THREAD

**Issue by RuLeiFei** [n1crack/vuefinder#52]
Hello Yusuf!
Thank you so much for your package, it's really a big deal, I found this solution recently and decided to apply it in my projects. 
I am very glad that your package has localization, but I could not find a button for `:select-button`, is it hard-coded text or do I need to add a line in the localization file?

![image](https://github.com/n1crack/vuefinder/assets/19463045/70e8cd2b-e24e-46c4-8ff6-10ee43573d54)

**Comment by n1crack** [comment]
Here it is:

https://github.com/n1crack/vuefinder/blob/80cfd9d2ce112327d3b99e22438ba5442b0e663b/src/components/Statusbar.vue#L25

`"Select": "Select" ` should be added to translation files. I think we missed this one.

**Comment by RuLeiFei** [comment]
Oh! Thanks for the quick response, otherwise your package works fine, I integrated it into WangEditor as a file manager and it's just magic compared to other solutions.

**Comment by n1crack** [comment]
Thx, I will add the translations asap (probably tomorrow).

**Comment by n1crack** [comment]
It is added.
