### ISSUE TITLE
Bug: file uploading doesn't work with any type of files

### ISSUE THREAD

**Issue by vinraelll** [n1crack/vuefinder#59]
- Vuefinder **2.4.3 (also tried 2.2.7)**
- Nuxt **3.11.2**
- Vue **3.4.27**
- Yarn **4.2.2**
- Node **20.13.1**

When trying to upload any type of files get an error from Uppy package dependency used in Vuefinder:
<img width="452" alt="image" src="https://github.com/n1crack/vuefinder/assets/53097647/33073f4d-4da0-446a-b238-8704bc16d376">
I've tried to upload various types of images (webp, png, jpg), audio files (mp3), but result remains the same.
<img width="687" alt="image" src="https://github.com/n1crack/vuefinder/assets/53097647/0787c732-5df8-4744-ab19-8e24b27dbc80">
Vuefinder usage in my project: 
<img width="388" alt="image" src="https://github.com/n1crack/vuefinder/assets/53097647/a060be26-6aba-42cc-b970-abbec8e02645">
<img width="626" alt="image" src="https://github.com/n1crack/vuefinder/assets/53097647/6d722468-1dea-45bf-a764-2e76decf13a0">

**Comment by n1crack** [comment]
It seems it is related to backend server. 

I'll check it asap. Until then; be sure to have latest version of php backend library.

**Comment by vinraelll** [comment]
> be sure to have latest version of php backend library.

Updated lib on our server to the latest version. Unfortunately, the issue remains.
![telegram-cloud-photo-size-2-5420320093184844013-x](https://github.com/n1crack/vuefinder/assets/53097647/3a1e362a-1a44-4494-80c8-689aa4b151ce)

**Comment by vinraelll** [comment]
After clicking on upload button the plugin makes three unsuccessful requests to the server and all have the same response.
<img width="581" alt="image" src="https://github.com/n1crack/vuefinder/assets/53097647/7dab864e-9c27-4ce4-925d-6f4689521c80">

**Comment by n1crack** [comment]
Something happens here, If you can remove try-catch blog, you can see the actual error. Not sure what happens for now. 


https://github.com/n1crack/vuefinder-php/blob/97562dd1895aee5f31a6607d4d68d43285cf8d93/src/VueFinder.php#L108-L124

**Comment by stereoalina** [comment]
Hello,

I believe I know what happened.

We have POST request /api/v1/remote-control-panel/file-manager?adapter=local&path=local%3A%2F%2Fpage_builder&q=upload
with payloaded image and content-type: application/json

The exception is thrown here:
![image](https://github.com/n1crack/vuefinder/assets/25963732/11d8730a-0194-496c-aba2-2a8e83b226bf)
![image](https://github.com/n1crack/vuefinder/assets/25963732/7d3f78b9-25a2-46cf-ab75-23400624a7e4)

I think no $this->request at this step. I've found where it inizializing:

![image](https://github.com/n1crack/vuefinder/assets/25963732/ff2573be-8974-4ce9-b6b4-634216b36ae4)

So when we have POST method and our content-type is not application/x-www-form-urlencoded, the "request" buddy has not inizialized.

**Comment by n1crack** [comment]
I will fix it tonight. Thx for reporting. 

I am planning to rewrite the backend library from scratch, when I have time, also considering a new backend package for Laravel with additional features.  

Also, need to create an OpenApi docs for backend.

**Comment by vinraelll** [comment]
Great, sounds good.

> I am planning to rewrite the backend library from scratch, when I have time, also considering a new backend package for Laravel with additional features.


> I will fix it tonight. Thx for reporting.

Thanks for rapid response

**Comment by n1crack** [comment]
Well, the problem was because of "Content-Type". It was using 'application/json' instead of 'multipart/form-data" when uploading.

It should work for now. I'll refactor the code asap as I mention above.

**Comment by vinraelll** [comment]
> It should work for now, just sent a fix.

Updated the package - all works fine for now, thanks. Files upload without any problems now. 
I guess, we can mark the issue as completed.
