### ISSUE TITLE
SFTP Surpport

### ISSUE THREAD

**Issue by imbraintl** [n1crack/vuefinder#64]
Hello, Can someone help me on how I can use this on sFTP or FTP with Javascript or Python

**Comment by n1crack** [comment]
Unfortunately, we have only php support as backend right now. You can check flysystem docs here: 

https://flysystem.thephpleague.com/docs/adapter/sftp-v3/

**Comment by n1crack** [comment]
Hi there,

Again, thank you for your interest. Previously, we only had PHP support as a backend. However, we are excited to announce that a community member has contributed a Python backend for our component!

You can check out the new Python backend here: [vuefinder-wsgi](https://github.com/abichinger/vuefinder-wsgi).

A big thank you to @abichinger for this contribution! We encourage you to try it out and provide any feedback or improvements you may have.

If you have any further questions or need assistance, please don't hesitate to ask.
