### ISSUE TITLE
attributes not work at all

### ISSUE THREAD

**Issue by afozooni** [n1crack/vuefinder#7]
Hey mate, I hope you were ok.

None of attributes (ex. dark, locale) are working! Please check these attr's and If you have a free time please fix there.
Thank you

**Comment by n1crack** [comment]
It seems they are working. Can you clear your browsers localstorage and try again? 

also you can check the online demo code here :  https://github.com/n1crack/vuefinder.ozdemir.be

**Comment by afozooni** [comment]
Thank you, I solved this!
I think that was packages conflic or smth like that because when I delete node_modules folder and re-install that, this was fixed.
