### ISSUE TITLE
Error removeListener with v-show 

### ISSUE THREAD

**Issue by Lucas-Justine** [n1crack/vuefinder#73]
An error is generated when the component is no longer displayed with a v-if, for example. 

![image](https://github.com/user-attachments/assets/7b5358af-1bf1-4e2d-89c7-7fefa135bbe5)

I think it's because the **ref="root "** no longer exists in the unmounted function in useHotkeyActions.js composable.

**Comment by ximepa** [comment]
same issue

**Comment by ximepa** [comment]
> An error is generated when the component is no longer displayed with a v-if, for example.
> 
> ![image](https://private-user-images.githubusercontent.com/132840998/355178878-7b5358af-1bf1-4e2d-89c7-7fefa135bbe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzgwNzMsIm5iZiI6MTcyMjkzNzc3MywicGF0aCI6Ii8xMzI4NDA5OTgvMzU1MTc4ODc4LTdiNTM1OGFmLTFiZjEtNGUyZC04OWM3LTdmZWZhMTM1YmJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwOTQ5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGJmNDkwNGE1YmJjMzM1ODA4OWI0NzA4YjkyOTMxN2E3MzIxODEwNGMwZWM0ZTg2Yjg4NGMzNDM2MGRiZDgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._y0HnwZPle-Q9L-31fwpLVCPeJE5scXGw8M8wtB2e1o)
> 
> I think it's because the **ref="root "** no longer exists in the unmounted function in useHotkeyActions.js composable.

did you have a solution?

**Comment by LucasJustine** [comment]
> > An error is generated when the component is no longer displayed with a v-if, for example.
> > ![image](https://private-user-images.githubusercontent.com/132840998/355178878-7b5358af-1bf1-4e2d-89c7-7fefa135bbe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzgwNzMsIm5iZiI6MTcyMjkzNzc3MywicGF0aCI6Ii8xMzI4NDA5OTgvMzU1MTc4ODc4LTdiNTM1OGFmLTFiZjEtNGUyZC04OWM3LTdmZWZhMTM1YmJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwOTQ5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGJmNDkwNGE1YmJjMzM1ODA4OWI0NzA4YjkyOTMxN2E3MzIxODEwNGMwZWM0ZTg2Yjg4NGMzNDM2MGRiZDgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._y0HnwZPle-Q9L-31fwpLVCPeJE5scXGw8M8wtB2e1o)
> > I think it's because the **ref="root "** no longer exists in the unmounted function in useHotkeyActions.js composable.
> 
> do you have a solution?

I modified the code but only temporarily so as not to get any errors. 
I've added a **question mark** for each line with an error. I haven't had time to look into a real solution to the problem

**Comment by ximepa** [comment]
> An error is generated when the component is no longer displayed with a v-if, for example.
> 
> ![image](https://private-user-images.githubusercontent.com/132840998/355178878-7b5358af-1bf1-4e2d-89c7-7fefa135bbe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTEyOTMsIm5iZiI6MTcyMzExMDk5MywicGF0aCI6Ii8xMzI4NDA5OTgvMzU1MTc4ODc4LTdiNTM1OGFmLTFiZjEtNGUyZC04OWM3LTdmZWZhMTM1YmJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwOTU2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTc5N2U0MzBmODBhZGYxZDI4NzFlMjA4ZjY5NzJmNzkyNDcxODgwMTc0ZjRiOTBjOTdmMzZmZDNlODQ3ZTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2IqMY8J7MiPxZln1zRY0FULLoLfZWG9EUGwKtlK7STU)
> 
> I think it's because the **ref="root "** no longer exists in the unmounted function in useHotkeyActions.js composable.

understood

**Comment by n1crack** [comment]
Fixed https://github.com/n1crack/vuefinder/commit/65d695d5868416843cd611dcad78855c1451fc5c
